# Generated by Django 5.2.5 on 2026-06-24 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المشروع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('client', models.CharField(blank=True, max_length=150, verbose_name='العميل')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('completed', 'مكتمل'), ('paused', 'متوقف'), ('planning', 'تخطيط')], default='planning', max_length=20, verbose_name='الحالة')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='نسبة الإنجاز %')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الميزانية (ريال)')),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المصروف (ريال)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='مدير المشروع')),
                ('team', models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='الفريق')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='المهمة')),
                ('status', models.CharField(choices=[('todo', 'لم يبدأ'), ('in_progress', 'جارٍ'), ('done', 'مكتمل')], default='todo', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'verbose_name': 'مهمة',
                'verbose_name_plural': 'المهام',
            },
        ),
    ]
