# Generated by Django 5.2.5 on 2026-06-24 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=100, verbose_name='اسم العائلة')),
                ('job_title', models.CharField(max_length=150, verbose_name='المسمى الوظيفي')),
                ('nationality', models.CharField(choices=[('سعودي', 'سعودي'), ('مقيم', 'مقيم'), ('مصري', 'مصري'), ('يمني', 'يمني'), ('باكستاني', 'باكستاني'), ('هندي', 'هندي'), ('بنغلاديشي', 'بنغلاديشي'), ('فلبيني', 'فلبيني'), ('سوداني', 'سوداني'), ('سوري', 'سوري'), ('أردني', 'أردني'), ('لبناني', 'لبناني'), ('عراقي', 'عراقي'), ('تركي', 'تركي'), ('إندونيسي', 'إندونيسي'), ('إثيوبي', 'إثيوبي'), ('أخرى', 'أخرى')], default='سعودي', max_length=50, verbose_name='الجنسية')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], default='M', max_length=1, verbose_name='الجنس')),
                ('id_type', models.CharField(choices=[('NID', 'هوية وطنية'), ('IQA', 'إقامة'), ('PAS', 'جواز سفر')], default='NID', max_length=3, verbose_name='نوع الإثبات')),
                ('id_number', models.CharField(max_length=50, verbose_name='رقم الإثبات')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('employment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التوظيف')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('status', models.CharField(choices=[('A', 'نشط'), ('U', 'غير نشط')], default='A', max_length=1, verbose_name='الحالة')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employees/photos/', verbose_name='الصورة الشخصية')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب النظام')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفين',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
