# Generated by Django 5.2.5 on 2026-06-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_quotation_quotationline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الخدمة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف التفصيلي')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='الوحدة')),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='السعر الافتراضي')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='التصنيف')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
                'ordering': ['category', 'name'],
            },
        ),
    ]
