# Generated by Django 5.2.5 on 2026-06-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('individual', 'فرد'), ('company', 'شركة')], default='individual', max_length=20, verbose_name='نوع العميل')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='رقم الهوية')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='clients/logos/', verbose_name='شعار الشركة')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('commercial_registration', models.CharField(blank=True, max_length=50, verbose_name='السجل التجاري')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='الشخص المسؤول')),
                ('contact_person_title', models.CharField(blank=True, max_length=100, verbose_name='المسمى الوظيفي')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['-created_at'],
            },
        ),
    ]
