"""
Django settings for bconstproject project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Railway injects RAILWAY_* env vars automatically on every deploy — no manual
# configuration needed to tell production and local dev apart.
IS_PRODUCTION = any(k.startswith('RAILWAY_') for k in os.environ)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y(58+5$m60v9mt&%)wc0oxv6%ojr)cm&6!2f^zb*eh(tia$=!-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not IS_PRODUCTION

ALLOWED_HOSTS = ['bconstructions.org', 'www.bconstructions.org', '.up.railway.app', 'localhost', '127.0.0.1']

CSRF_TRUSTED_ORIGINS = [
    'https://bconstructions.org',
    'https://www.bconstructions.org',
]

if IS_PRODUCTION:
    # Railway terminates TLS at its edge proxy and forwards plain HTTP internally,
    # so Django needs this header to know the original request was HTTPS —
    # without it SECURE_SSL_REDIRECT causes an infinite redirect loop.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # The Host header gunicorn actually sees is Railway's internal address, not the
    # public domain — without this, request.build_absolute_uri() (used e.g. for the
    # password-setup email link) generates a broken http://127.0.0.1:8000/... URL.
    # Safe to trust here: Railway's edge proxy sets/overwrites this header itself,
    # and Django still validates the resolved host against ALLOWED_HOSTS either way.
    USE_X_FORWARDED_HOST = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Conservative initial value (1 day, not the usual 1 year) — HSTS is
    # enforced client-side and hard to undo quickly if anything's misconfigured.
    SECURE_HSTS_SECONDS = 60 * 60 * 24
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',
    'website',
    'system',
    'projects',
    'clients',
    'employees',
    'accounting',
    'inventory',
    'marketing',
    'company',
    'invoices',
    'reports',
    'namadhj',
    'attendance',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise here
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bconstproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Point to the 'templates' folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'company.context_processors.company_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'bconstproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'railway',
        'USER': 'postgres',
        'PASSWORD': 'INGcLSJJbTyvaixufygziXipyClBsZjQ',
        'HOST': 'hayabusa.proxy.rlwy.net',
        'PORT': '16451',
        'CONN_MAX_AGE': 600,
    }
}

# In-process cache — used for login-attempt throttling and short-lived report caching
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Riyadh'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = []

STATIC_ROOT = BASE_DIR / 'staticfiles'  # For production

# Plain (non-hashed) static storage. Compressed/hashed manifest storage was tried and
# reverted: several {% static %} references across the public site (studio.html's
# service icons, a hero poster image) point at files that were never actually added
# to the repo, and manifest storage hard-fails template rendering on any missing file
# — unlike plain storage, which just resolves to a URL without checking existence.
# Revisit once those missing assets are tracked down and added.
#
# Django itself only reads STORAGES (below) — this legacy attribute exists solely
# because django-cloudinary-storage's own collectstatic override reads it directly
# and crashes with AttributeError if it's undefined.
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

WHITENOISE_AUTOREFRESH = True  # reload static files from disk on each request (dev mode)



# Media files (user-uploaded) — stored on Cloudinary
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'ddfgomhhd',
    'API_KEY': '167277254993451',
    'API_SECRET': 'psAXMHXqI5MzjpR0K2krjJetCRU',
    'PREFIX': '',
}
STORAGES = {
    'default': {
        'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')





# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL          = '/system/'
LOGIN_REDIRECT_URL = '/projects/'
LOGOUT_REDIRECT_URL = '/system/'


# للاستخدام مع Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'hinp.notify@gmail.com'
EMAIL_HOST_PASSWORD = 'jdus jvct rvua fprb'
DEFAULT_FROM_EMAIL = 'باء البناء <hinp.notify@gmail.com>'
