from django.urls import path
from . import views

urlpatterns = [
    path('', views.invoices_home, name='invoices_home'),
    path('create/', views.invoice_create, name='inv_create'),
    path('<int:pk>/edit/', views.invoice_edit, name='inv_edit'),
    path('<int:pk>/', views.invoice_detail, name='inv_detail'),
    path('<int:pk>/print/', views.invoice_print, name='inv_print'),
    path('<int:pk>/finalize/', views.invoice_finalize, name='inv_finalize'),
    path('<int:pk>/cancel/', views.invoice_cancel, name='inv_cancel'),
    path('<int:pk>/delete/', views.invoice_delete, name='inv_delete'),
    path('<int:pk>/pay/', views.payment_add, name='inv_pay'),
    path('receipts/<int:pk>/print/', views.receipt_print, name='rec_print'),
    path('receipts/<int:pk>/delete/', views.receipt_delete, name='rec_delete'),
    path('receipts/<int:pk>/edit/', views.receipt_edit, name='rec_edit'),
    path('api/clients/', views.client_search, name='inv_client_search'),
    path('api/projects/', views.project_search, name='inv_project_search'),
    path('api/items/', views.item_search, name='inv_item_search'),
    path('api/services/', views.service_search, name='inv_service_search'),
    path('api/categories/', views.category_list, name='inv_category_list'),
    path('categories/create/', views.category_create, name='category_create'),
    path('categories/<str:name>/delete/', views.category_delete, name='category_delete'),
    path('services/create/', views.service_create, name='service_create'),
    path('services/<int:pk>/edit/', views.service_edit, name='service_edit'),
    path('services/<int:pk>/delete/', views.service_delete, name='service_delete'),
    path('<int:pk>/change-client/', views.invoice_change_client, name='inv_change_client'),
    path('<int:pk>/notes/add/', views.invoice_note_add, name='inv_note_add'),
    path('notes/<int:note_pk>/delete/', views.invoice_note_delete, name='inv_note_delete'),
    path('notes/<int:note_pk>/print/', views.invoice_note_print, name='inv_note_print'),
    # عروض الأسعار
    path('quotes/', views.quotes_list, name='quotes_list'),
    path('quotes/create/', views.quote_create, name='quote_create'),
    path('quotes/<int:pk>/edit/', views.quote_edit, name='quote_edit'),
    path('quotes/<int:pk>/', views.quote_detail, name='quote_detail'),
    path('quotes/<int:pk>/print/', views.quote_print, name='quote_print'),
    path('quotes/<int:pk>/send/', views.quote_send, name='quote_send'),
    path('quotes/<int:pk>/accept/', views.quote_accept, name='quote_accept'),
    path('quotes/<int:pk>/reject/', views.quote_reject, name='quote_reject'),
    path('quotes/<int:pk>/convert/', views.quote_convert, name='quote_convert'),
    path('quotes/<int:pk>/delete/', views.quote_delete, name='quote_delete'),
]
