# Generated by Django 5.2.5 on 2026-06-29 12:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التصنيف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تصنيف نموذج',
                'verbose_name_plural': 'تصنيفات النماذج',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LetterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التصنيف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تصنيف خطاب',
                'verbose_name_plural': 'تصنيفات الخطابات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان الرئيسي')),
                ('content', models.TextField(verbose_name='النص العام')),
                ('footer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الشخص / ملاحظة نهائية')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='namadhj.formcategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'نموذج',
                'verbose_name_plural': 'النماذج',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_number', models.CharField(max_length=100, verbose_name='رقم الخطاب')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان الخطاب')),
                ('recipient', models.CharField(blank=True, max_length=300, null=True, verbose_name='المرسل إليه')),
                ('subject', models.CharField(blank=True, max_length=300, null=True, verbose_name='الموضوع')),
                ('content', models.TextField(verbose_name='نص الخطاب')),
                ('footer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الموقّع / ملاحظة نهائية')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='namadhj.lettercategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'خطاب',
                'verbose_name_plural': 'الخطابات',
                'ordering': ['-created_at'],
            },
        ),
    ]
