# Generated by Django 5.2.5 on 2026-06-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('license', 'ترخيص'), ('contract', 'عقد'), ('document', 'مستند عام')], default='document', max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='company/docs/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('company_name_ar', models.CharField(blank=True, max_length=255)),
                ('company_name_en', models.CharField(blank=True, max_length=255)),
                ('unified_number', models.CharField(blank=True, max_length=20)),
                ('cr_number', models.CharField(blank=True, max_length=20)),
                ('cr_issue_date', models.DateField(blank=True, null=True)),
                ('municipality_license', models.CharField(blank=True, max_length=100)),
                ('tax_registration_number', models.CharField(blank=True, max_length=50)),
                ('facility_address', models.TextField(blank=True)),
                ('address_building_number', models.CharField(blank=True, max_length=20)),
                ('address_street', models.CharField(blank=True, max_length=255)),
                ('address_district', models.CharField(blank=True, max_length=255)),
                ('address_city', models.CharField(blank=True, max_length=100)),
                ('address_postal_code', models.CharField(blank=True, max_length=10)),
                ('manager_name', models.CharField(blank=True, max_length=255)),
                ('manager_nationality', models.CharField(blank=True, max_length=100)),
                ('manager_id', models.CharField(blank=True, max_length=50)),
                ('manager_mobile', models.CharField(blank=True, max_length=20)),
                ('manager_email', models.EmailField(blank=True, max_length=254)),
                ('pr_mobile', models.CharField(blank=True, max_length=20)),
                ('pr_email', models.EmailField(blank=True, max_length=254)),
                ('marketing_mobile', models.CharField(blank=True, max_length=20)),
                ('marketing_email', models.EmailField(blank=True, max_length=254)),
                ('hr_email', models.EmailField(blank=True, max_length=254)),
                ('instagram', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('snapchat', models.URLField(blank=True)),
                ('google_maps_link', models.URLField(blank=True)),
                ('website_link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'إعدادات الشركة',
            },
        ),
    ]
