# Generated by Django 5.2.5 on 2026-06-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم طريقة الدفع')),
                ('payment_type', models.CharField(choices=[('immediate', 'فوري'), ('deferred', 'آجل')], default='immediate', max_length=20, verbose_name='نوع الدفع')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='اسم الشركة')),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الرسوم %')),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الرسوم الثابتة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'طريقة دفع',
                'verbose_name_plural': 'طرق الدفع',
                'ordering': ['name'],
            },
        ),
    ]
