# Generated by Django 5.2.5 on 2026-06-24 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('asset', 'أصول'), ('liability', 'خصوم'), ('equity', 'حقوق ملكية'), ('revenue', 'إيرادات'), ('expense', 'مصروفات')], max_length=20, unique=True, verbose_name='التصنيف')),
                ('normal_balance', models.CharField(choices=[('debit', 'مدين'), ('credit', 'دائن')], max_length=10, verbose_name='الرصيد الطبيعي')),
            ],
            options={
                'verbose_name': 'نوع الحساب',
                'verbose_name_plural': 'أنواع الحسابات',
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='الرمز')),
                ('type', models.CharField(choices=[('project', 'مشروع'), ('admin', 'إدارة'), ('shared', 'مشترك')], default='project', max_length=20, verbose_name='النوع')),
            ],
            options={
                'verbose_name': 'مركز تكلفة',
                'verbose_name_plural': 'مراكز التكلفة',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رقم الحساب')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الحساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_system', models.BooleanField(default=False, verbose_name='حساب نظام')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account', verbose_name='الحساب الرئيسي')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.accounttype', verbose_name='نوع الحساب')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'دليل الحسابات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الأصل')),
                ('category', models.CharField(choices=[('heavy_equipment', 'معدات ثقيلة'), ('vehicles', 'مركبات'), ('tools', 'أدوات وعدد'), ('it_equipment', 'معدات تقنية'), ('furniture', 'أثاث'), ('other', 'أخرى')], max_length=30, verbose_name='الفئة')),
                ('purchase_date', models.DateField(verbose_name='تاريخ الشراء')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='التكلفة الأصلية')),
                ('useful_life_months', models.PositiveIntegerField(verbose_name='العمر الافتراضي (أشهر)')),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='القيمة التخريدية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_assets', to='accounting.costcenter', verbose_name='مركز التكلفة')),
            ],
            options={
                'verbose_name': 'أصل ثابت',
                'verbose_name_plural': 'الأصول الثابتة',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='رقم القيد')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('description', models.CharField(max_length=500, verbose_name='البيان')),
                ('source_type', models.CharField(choices=[('invoice', 'فاتورة'), ('receipt', 'سند قبض'), ('purchase', 'مشتريات'), ('payment', 'دفعة'), ('payroll', 'رواتب'), ('depreciation', 'استهلاك'), ('manual', 'قيد يدوي')], default='manual', max_length=30, verbose_name='نوع المصدر')),
                ('is_posted', models.BooleanField(default=False, verbose_name='معتمد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals', to='accounting.costcenter', verbose_name='مركز التكلفة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'قيد يومية',
                'verbose_name_plural': 'قيود اليومية',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='دائن')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='ملاحظة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account', verbose_name='الحساب')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journal', verbose_name='القيد')),
            ],
            options={
                'verbose_name': 'سطر قيد',
                'verbose_name_plural': 'سطور القيود',
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('month', models.PositiveIntegerField(verbose_name='الشهر')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحّل'), ('void', 'ملغى')], default='draft', max_length=10, verbose_name='الحالة')),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي الرواتب')),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='صافي المدفوع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'مسير رواتب',
                'verbose_name_plural': 'مسيرات الرواتب',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('month', models.PositiveIntegerField(verbose_name='الشهر')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مقفلة')], default='open', max_length=10, verbose_name='الحالة')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإقفال')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to=settings.AUTH_USER_MODEL, verbose_name='أقفلها')),
            ],
            options={
                'verbose_name': 'فترة محاسبية',
                'verbose_name_plural': 'الفترات المحاسبية',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب الأساسي')),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='البدلات')),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الاستقطاعات')),
                ('deduction_note', models.CharField(blank=True, max_length=255, verbose_name='سبب الاستقطاع')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='البونص')),
                ('bonus_note', models.CharField(blank=True, max_length=255, verbose_name='سبب البونص')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='الموظف')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.payrollrun', verbose_name='المسير')),
            ],
            options={
                'verbose_name': 'سطر مسير',
                'verbose_name_plural': 'سطور المسير',
                'unique_together': {('payroll', 'employee')},
            },
        ),
    ]
