# Generated by Django 5.2.5 on 2026-07-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='الوقت'),
        ),
    ]
